### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by jrios6** [halfwhole/nlb-books#2]
I noticed that a Postgres Database is required for storing of records in the DB. Could you provide a initialization script for creation of the DB and tables and provide instructions for setting this up in the README?

P.S. I think this is a great project, keep it going!

**Comment by halfwhole** [comment]
Hey there, thanks for your interest! Sorry that this reply comes far too late, I wouldn't have noticed it at all if not for a recent dependabot pull request in this repo.

I've updated the readme with the setup instructions for the database. Running a simple `npx sequelize db:create` and `npx sequelize db:migrate` should do the job of setting it up. This seems to work fine here on Ubuntu, though it might have trouble on other OSes.

In any case, I have a [newer repo](https://github.com/halfwhole/nlb-telegram-bot) for a telegram bot that does the same, but better (imo)! I probably won't be returning to update this project any further unfortunately, given how terribly complex and brittle it turned out to be, though it served me well for many months.
